language: ruby
rvm:
- 2.2.2
before_install: gem install jekyll html-proofer
script: bundle exec jekyll build && htmlproofer --disable-external --check-html ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
