# Site settings
title: Question2Answer documentation
url: http://docs.question2answer.org
baseurl: /
permalink: pretty
exclude: [vendor]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Menu layout
nav:
  main:
    - name: Install
      path: /install/
    - name: Translate
      path: /translate/
    - name: Themes
      path: /themes/
    - name: Plugins
      path: /plugins/
    - name: Code
      path: /code/external/
    - name: Contribute
      path: /contribute/
    - name: Add-Ons
      path: /addons/
    - name: Services
      path: /services/

  install:
    - name: Basic Install
      path: /install/
    - name: WordPress
      path: /install/wordpress/
    - name: Single Sign-On
      path: /install/single-sign-on/
    - name: Upgrading
      path: /install/upgrade/
    - name: Optimization
      path: /install/optimize/
    - name: Security
      path: /install/security/

  plugins:
    - name: Overview
      path: /plugins/
    - name: Modules
      path: /plugins/modules/
    - name: Layers
      path: /plugins/layers/
    - name: Overrides
      path: /plugins/overrides/
    - name: Plugin Tutorial
      path: /plugins/tutorial/

  code:
    - name: External
      path: /code/external/
    - name: Functions
      path: /code/functions/
    - name: App Structure
      path: /code/structure/

  contribute:
    - name: Issues
      path: /contribute/
    - name: Coding Style
      path: /contribute/coding-style/
    - name: Unit tests
      path: /contribute/unit-tests/
    - name: Documentation
      path: /contribute/docs/


